import { expect } from 'chai';
import {
  appImageFilesystemOffset,
  desktopEntryExec,
  desktopEntryViolations,
  desktopExecArguments,
  isSquashfsSuperblock,
  launcherViolations,
  parseArMembers,
} from '../scripts/linux-launcher-policy.js';

/** The entry electron-builder produces when `appImage.executableArgs` is set. */
const SANDBOXED_APPIMAGE_ENTRY = [
  '[Desktop Entry]',
  'Name=DocBlocks',
  'Exec=AppRun %U',
  'Terminal=false',
  'Type=Application',
  'Icon=docblocks-desktop',
  'StartupWMClass=DocBlocks',
  'X-AppImage-Version=2.6.2',
  'Categories=Office;',
  'MimeType=text/markdown;application/vnd.docblocks+zip;x-scheme-handler/docblocks;',
  '',
].join('\n');

/** The entry electron-builder's AppImage default produced for 2.6.2. */
const UNSANDBOXED_APPIMAGE_ENTRY = SANDBOXED_APPIMAGE_ENTRY.replace(
  'Exec=AppRun %U',
  'Exec=AppRun --no-sandbox %U',
);

const DEB_ENTRY = SANDBOXED_APPIMAGE_ENTRY.replace(
  'Exec=AppRun %U',
  'Exec=/opt/DocBlocks/docblocks-desktop %U',
);

describe('packaged Linux launcher policy', () => {
  describe('reading the Exec key', () => {
    it('reads the launch command from the main desktop group', () => {
      expect(desktopEntryExec(SANDBOXED_APPIMAGE_ENTRY)).to.equal('AppRun %U');
      expect(desktopEntryExec(DEB_ENTRY)).to.equal('/opt/DocBlocks/docblocks-desktop %U');
    });

    it('ignores Exec keys belonging to later action groups', () => {
      const withAction = [
        SANDBOXED_APPIMAGE_ENTRY,
        '[Desktop Action new-window]',
        'Name=New Window',
        'Exec=AppRun --new-window %U',
        '',
      ].join('\n');
      expect(desktopEntryExec(withAction)).to.equal('AppRun %U');
    });

    it('ignores comments and blank lines before the key', () => {
      const commented = ['# generated by electron-builder', '', SANDBOXED_APPIMAGE_ENTRY].join(
        '\n',
      );
      expect(desktopEntryExec(commented)).to.equal('AppRun %U');
    });

    it('reports a missing key rather than guessing', () => {
      expect(desktopEntryExec('[Desktop Entry]\nName=DocBlocks\n')).to.equal(null);
      expect(desktopEntryExec('Exec=AppRun %U\n')).to.equal(null);
    });
  });

  describe('splitting the Exec value', () => {
    it('splits a plain command line', () => {
      expect(desktopExecArguments('AppRun --no-sandbox %U')).to.deep.equal([
        'AppRun',
        '--no-sandbox',
        '%U',
      ]);
    });

    it('unwraps the double quotes the freedesktop spec requires for reserved characters', () => {
      expect(desktopExecArguments('"/opt/Doc Blocks/docblocks" "--no-sandbox" %U')).to.deep.equal([
        '/opt/Doc Blocks/docblocks',
        '--no-sandbox',
        '%U',
      ]);
    });

    it('honors backslash escapes inside a quoted argument', () => {
      expect(desktopExecArguments('"/opt/Doc\\"Blocks/run" %U')).to.deep.equal([
        '/opt/Doc"Blocks/run',
        '%U',
      ]);
    });

    it('collapses repeated whitespace without emitting empty arguments', () => {
      expect(desktopExecArguments('  AppRun   %U  ')).to.deep.equal(['AppRun', '%U']);
    });
  });

  describe('the sandbox rule', () => {
    it('accepts the launcher electron-builder writes with explicit executableArgs', () => {
      expect(
        desktopEntryViolations({ source: 'x64.AppImage', text: SANDBOXED_APPIMAGE_ENTRY }),
      ).to.deep.equal([]);
      expect(desktopEntryViolations({ source: 'amd64.deb', text: DEB_ENTRY })).to.deep.equal([]);
    });

    it('rejects the --no-sandbox launcher that shipped in the 2.6.2 candidate', () => {
      const violations = desktopEntryViolations({
        source: 'DocBlocks-2.6.2-linux-x86_64.AppImage:docblocks-desktop.desktop',
        text: UNSANDBOXED_APPIMAGE_ENTRY,
      });
      expect(violations).to.have.lengthOf(1);
      expect(violations[0]?.source).to.equal(
        'DocBlocks-2.6.2-linux-x86_64.AppImage:docblocks-desktop.desktop',
      );
      expect(violations[0]?.detail).to.contain('--no-sandbox');
      expect(violations[0]?.detail).to.contain('Exec=AppRun --no-sandbox %U'.slice(5));
    });

    it('rejects a quoted sandbox flag that an unquoted scan would miss', () => {
      const quoted = SANDBOXED_APPIMAGE_ENTRY.replace(
        'Exec=AppRun %U',
        'Exec=AppRun "--no-sandbox" %U',
      );
      expect(desktopEntryViolations({ source: 'quoted.AppImage', text: quoted })).to.have.lengthOf(
        1,
      );
    });

    it('rejects every flag that turns off process isolation, not only --no-sandbox', () => {
      for (const flag of [
        '--disable-setuid-sandbox',
        '--disable-gpu-sandbox',
        '--disable-namespace-sandbox',
        '--disable-seccomp-filter-sandbox',
      ]) {
        const text = SANDBOXED_APPIMAGE_ENTRY.replace('Exec=AppRun %U', `Exec=AppRun ${flag} %U`);
        expect(desktopEntryViolations({ source: `${flag}.AppImage`, text }), flag).to.have.lengthOf(
          1,
        );
      }
    });

    it('does not mistake an unrelated flag for a sandbox flag', () => {
      const text = SANDBOXED_APPIMAGE_ENTRY.replace(
        'Exec=AppRun %U',
        'Exec=AppRun --ozone-platform-hint=auto %U',
      );
      expect(desktopEntryViolations({ source: 'wayland.AppImage', text })).to.deep.equal([]);
    });

    it('treats an unreadable entry as a violation', () => {
      expect(
        desktopEntryViolations({ source: 'broken.AppImage', text: '[Desktop Entry]\nName=X\n' }),
      ).to.have.lengthOf(1);
    });
  });

  describe('the artifact sweep', () => {
    it('reports every offending launcher across artifacts', () => {
      const violations = launcherViolations([
        { source: 'x86_64.AppImage', text: UNSANDBOXED_APPIMAGE_ENTRY },
        { source: 'arm64.AppImage', text: UNSANDBOXED_APPIMAGE_ENTRY },
        { source: 'amd64.deb', text: DEB_ENTRY },
      ]);
      expect(violations.map((violation) => violation.source)).to.deep.equal([
        'x86_64.AppImage',
        'arm64.AppImage',
      ]);
    });

    it('fails when nothing was inspected, so a mis-globbed directory cannot pass', () => {
      const violations = launcherViolations([]);
      expect(violations).to.have.lengthOf(1);
      expect(violations[0]?.detail).to.contain('no packaged desktop entries');
    });
  });

  describe('locating the filesystem inside an AppImage', () => {
    function elfHeader(sectionHeaderOffset: number, entrySize: number, count: number): Buffer {
      const header = Buffer.alloc(64);
      header.writeUInt32BE(0x7f454c46, 0);
      header[4] = 2; // 64-bit
      header[5] = 1; // little-endian
      header.writeBigUInt64LE(BigInt(sectionHeaderOffset), 0x28);
      header.writeUInt16LE(entrySize, 0x3a);
      header.writeUInt16LE(count, 0x3c);
      return header;
    }

    it('computes the offset past the ELF section headers', () => {
      // The real 2.6.0 x86_64 AppImage: 0x2d0c8 + 64 * 29 = 188392.
      expect(appImageFilesystemOffset(elfHeader(186536, 64, 29))).to.equal(188392);
    });

    it('rejects a file that is not a 64-bit little-endian ELF runtime', () => {
      expect(() => appImageFilesystemOffset(Buffer.alloc(64))).to.throw(/not an ELF/u);
      const bigEndian = elfHeader(186536, 64, 29);
      bigEndian[5] = 2;
      expect(() => appImageFilesystemOffset(bigEndian)).to.throw(/little-endian/u);
      const thirtyTwoBit = elfHeader(186536, 64, 29);
      thirtyTwoBit[4] = 1;
      expect(() => appImageFilesystemOffset(thirtyTwoBit)).to.throw(/64-bit/u);
    });

    it('recognizes the SquashFS superblock that must sit at that offset', () => {
      expect(isSquashfsSuperblock(Buffer.from([0x68, 0x73, 0x71, 0x73]))).to.equal(true);
      expect(isSquashfsSuperblock(Buffer.from([0x00, 0x00, 0x00, 0x00]))).to.equal(false);
      expect(isSquashfsSuperblock(Buffer.alloc(2))).to.equal(false);
    });
  });

  describe('locating the payload inside a Debian package', () => {
    function arArchive(members: readonly { name: string; body: string }[]): Buffer {
      const parts: Buffer[] = [Buffer.from('!<arch>\n', 'ascii')];
      for (const member of members) {
        const body = Buffer.from(member.body, 'utf8');
        const header = Buffer.alloc(60, 0x20);
        header.write(member.name, 0, 'ascii');
        header.write('0', 16, 'ascii');
        header.write(String(body.length), 48, 'ascii');
        header.write('`\n', 58, 'ascii');
        parts.push(header, body);
        if (body.length % 2 === 1) parts.push(Buffer.from('\n', 'ascii'));
      }
      return Buffer.concat(parts);
    }

    it('locates the data tarball a real package carries', () => {
      const archive = arArchive([
        { name: 'debian-binary', body: '2.0\n' },
        { name: 'control.tar.xz', body: 'control' },
        { name: 'data.tar.xz', body: 'payload' },
      ]);
      const members = parseArMembers(archive);
      expect(members.map((member) => member.name)).to.deep.equal([
        'debian-binary',
        'control.tar.xz',
        'data.tar.xz',
      ]);
      const data = members[2];
      expect(data).to.not.equal(undefined);
      expect(archive.subarray(data!.offset, data!.offset + data!.size).toString()).to.equal(
        'payload',
      );
    });

    it('reads GNU ar member names, which carry a trailing slash', () => {
      const archive = arArchive([{ name: 'data.tar.xz/', body: 'payload' }]);
      expect(parseArMembers(archive).map((member) => member.name)).to.deep.equal(['data.tar.xz']);
    });

    it('rejects a file that is not an ar archive', () => {
      expect(() => parseArMembers(Buffer.from('not a deb'))).to.throw(/not an ar archive/u);
    });
  });
});
