import type { Page } from '@playwright/test';
import { openInitializedSite } from './helpers/site.js';
import { expect, test } from './helpers/test.js';

/**
 * Workspace settings end to end on the site (an IndexedDB workspace, which
 * cannot watch its store): saving settings writes `.docblocks/workspace.json`,
 * the catalog appears in the explorer without a manual refresh, and the
 * generated page opens read-only instead of being imported for editing.
 */

const CATALOG_TIMEOUT_MS = 30_000;

function treeRow(page: Page, path: string) {
  return page.locator(`.db-tree-row[data-path="${path}"], .db-tree-row[data-path="/${path}"]`);
}

async function openWorkspaceSettings(page: Page) {
  await page.locator('.db-ws-settings-btn').click();
  await page.getByRole('menuitem', { name: 'Workspace settings…' }).click();
  const dialog = page.getByRole('dialog', { name: 'Workspace settings' });
  await expect(dialog).toBeVisible();
  return dialog;
}

test.describe('workspace settings', () => {
  test('keeps a catalog of the workspace and opens it read-only', async ({ page }) => {
    await openInitializedSite(page);

    const dialog = await openWorkspaceSettings(page);
    await dialog.getByLabel('Default theme', { exact: true }).selectOption('warm-earth');
    await dialog.getByLabel('Catalog page').check();
    await dialog.getByLabel('Catalog data (JSON)').check();
    await dialog.getByLabel('Title', { exact: true }).fill('Field notes');
    await dialog.getByRole('button', { name: 'Save' }).click();
    await expect(dialog).toBeHidden();

    await expect(treeRow(page, 'index.html')).toBeVisible({ timeout: CATALOG_TIMEOUT_MS });
    await expect(treeRow(page, 'catalog.json')).toBeVisible();
    // The settings folder itself stays hidden like every dot-folder.
    await expect(treeRow(page, '.docblocks')).toHaveCount(0);

    // Reopening shows the saved values and the catalog's status.
    const reopened = await openWorkspaceSettings(page);
    await expect(reopened.getByLabel('Default theme', { exact: true })).toHaveValue('warm-earth');
    await expect(reopened.getByLabel('Title', { exact: true })).toHaveValue('Field notes');
    await expect(reopened.getByText(/Up to date · \d+ documents?/)).toBeVisible({
      timeout: CATALOG_TIMEOUT_MS,
    });
    await reopened.getByRole('button', { name: 'Cancel' }).click();

    // The catalog page opens as the rendered page itself, never as editable text.
    await treeRow(page, 'index.html').click();
    const editorArea = page.locator('.db-shell-editor-area');
    await expect(editorArea.getByText('Generated by DocBlocks · read-only.')).toBeVisible({
      timeout: 15_000,
    });
    const preview = page.frameLocator('iframe.db-generated-file-preview');
    await expect(preview.getByRole('heading', { name: 'Field notes' })).toBeVisible();
    await expect(preview.getByRole('link', { name: 'DocBlocks' })).toBeVisible();
    await expect(page.locator('.ProseMirror[contenteditable="true"]')).toHaveCount(0);
    await expect(page.locator('.monaco-editor')).toHaveCount(0);
    // Opening the page must not import it as an editable outside-in document.
    await expect(treeRow(page, 'index_files')).toHaveCount(0);

    // The catalog data is shown as read-only text with the same notice.
    await treeRow(page, 'catalog.json').click();
    await expect(editorArea.getByText('Generated by DocBlocks · read-only.')).toBeVisible({
      timeout: 15_000,
    });
    await expect(editorArea.getByText('catalog data is rebuilt', { exact: false })).toBeVisible();
  });
  test('shows an unthemed catalog page on white even in dark mode', async ({ page }) => {
    // The unthemed page sets dark text and (before Squisq paints a page
    // background) no background: on the app's dark surface it was unreadable.
    await page.emulateMedia({ colorScheme: 'dark' });
    await openInitializedSite(page);
    const dialog = await openWorkspaceSettings(page);
    await dialog.getByLabel('Catalog page').check();
    await dialog.getByRole('button', { name: 'Save' }).click();
    await expect(treeRow(page, 'index.html')).toBeVisible({ timeout: CATALOG_TIMEOUT_MS });

    await treeRow(page, 'index.html').click();
    const frame = page.locator('iframe.db-generated-file-preview');
    await expect(frame).toBeVisible({ timeout: 15_000 });
    await expect(frame).toHaveCSS('background-color', 'rgb(255, 255, 255)');
    await expect(frame).toHaveCSS('color-scheme', 'light');
    const body = page.frameLocator('iframe.db-generated-file-preview').locator('body');
    await expect(body).toHaveCSS('color', 'rgb(31, 41, 55)');
  });
});
