/**
 * Views for the workspace catalog files DocBlocks generates (`index.html`,
 * `catalog.json`). They are outputs, not documents: the page is shown as the
 * page it is, the data as read-only text, and both say where they come from.
 */

import type { ReactNode } from 'react';

export type GeneratedFileKind = 'catalog-html' | 'catalog-json';

export interface GeneratedFileNoticeProps {
  kind: GeneratedFileKind;
  /** Opens the workspace settings that control this file. */
  onOpenSettings?: () => void;
  /** Single-pane layouts: return to the file list. */
  onBack?: () => void;
}

export function GeneratedFileNotice({ kind, onOpenSettings, onBack }: GeneratedFileNoticeProps) {
  return (
    <div className="db-generated-file-notice" role="note">
      {onBack && (
        <button type="button" className="db-generated-file-back" onClick={onBack}>
          Back to files
        </button>
      )}
      <span className="db-generated-file-notice-text">
        <strong>Generated by DocBlocks · read-only.</strong>{' '}
        {kind === 'catalog-html'
          ? 'This catalog page is rebuilt from the documents in this folder as you save.'
          : 'This catalog data is rebuilt from the documents in this folder as you save.'}
      </span>
      {onOpenSettings && (
        <button type="button" className="db-git-secondary-btn" onClick={onOpenSettings}>
          Catalog settings…
        </button>
      )}
    </div>
  );
}

export interface GeneratedCatalogPageProps extends Omit<GeneratedFileNoticeProps, 'kind'> {
  /** The generated page's HTML, exactly as written to disk. */
  html: string;
  /** File name, for the frame's accessible name. */
  fileName: string;
}

/**
 * The catalog page rendered as itself. The frame is fully sandboxed — no
 * scripts, forms, popups, or same-origin access — so even a hand-crafted file
 * carrying the generator marker can only be looked at.
 */
export function GeneratedCatalogPage({ html, fileName, ...notice }: GeneratedCatalogPageProps) {
  return (
    <div className="db-generated-file">
      <GeneratedFileNotice kind="catalog-html" {...notice} />
      <iframe
        className="db-generated-file-preview"
        title={`${fileName} — generated catalog page`}
        sandbox=""
        referrerPolicy="no-referrer"
        srcDoc={html}
      />
    </div>
  );
}

export interface GeneratedFileFrameProps extends Partial<GeneratedFileNoticeProps> {
  children: ReactNode;
}

/** Adds the generated-file notice above an editor; renders children alone otherwise. */
export function GeneratedFileFrame({ kind, children, ...notice }: GeneratedFileFrameProps) {
  if (!kind) return <>{children}</>;
  return (
    <div className="db-generated-file">
      <GeneratedFileNotice kind={kind} {...notice} />
      <div className="db-generated-file-body">{children}</div>
    </div>
  );
}
