/**
 * Generated catalog files are read-only in the editor. This guard is the
 * last line of defense: even if an edit somehow reached a commit, a file
 * carrying the DocBlocks catalog marker is never overwritten by the editor.
 */

import {
  getFileSystemProviderV2,
  parseWorkspacePath,
  type FileSystemProvider,
} from '@bendyline/docblocks/filesystem';
import {
  isGeneratedCatalogHtml,
  isGeneratedCatalogJson,
} from '@bendyline/docblocks/workspace-settings';

const CATALOG_EXTENSION = /\.(?:html?|json)$/i;

export async function assertNotGeneratedCatalog(
  provider: FileSystemProvider,
  path: string,
): Promise<void> {
  if (!CATALOG_EXTENSION.test(path)) return;
  const providerV2 = getFileSystemProviderV2(provider);
  if (!providerV2) return;
  const file = await providerV2.readFile(parseWorkspacePath(path));
  if (!file) return;
  const head = new TextDecoder().decode(file.data.slice(0, 4096));
  if (isGeneratedCatalogHtml(head) || isGeneratedCatalogJson(head)) {
    throw new Error(
      `${path} is generated by the workspace catalog. Change it from Workspace settings instead.`,
    );
  }
}
