/**
 * Verify the desktop entries embedded in packaged Linux artifacts.
 *
 * The AppImage launcher flag this catches is generated by electron-builder at
 * package time rather than written into our configuration, so a configuration
 * check alone cannot prove the shipped bytes. Run this after packaging and
 * before uploading release assets:
 *
 *   npm run check:linux-launchers -w docblocks-desktop
 *   npm run check:linux-launchers -w docblocks-desktop -- <artifacts-dir>
 *
 * Every AppImage and .deb in the directory is inspected. Missing extraction
 * tooling fails the run: a launcher that was never read is not a launcher that
 * passed.
 */

import { spawnSync } from 'node:child_process';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, mkdtemp, open, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';
import { fileURLToPath } from 'node:url';
import {
  appImageFilesystemOffset,
  isSquashfsSuperblock,
  launcherViolations,
  parseArMembers,
  type DesktopEntry,
} from './linux-launcher-policy.js';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const defaultArtifactsDir = path.join(packageRoot, 'dist', 'artifacts');

interface CommandResult {
  readonly ok: boolean;
  readonly output: string;
}

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

function run(command: string, args: readonly string[]): CommandResult {
  const result = spawnSync(command, [...args], {
    encoding: 'utf8',
    windowsHide: true,
    maxBuffer: 16 * 1024 * 1024,
  });
  if (result.error) {
    return { ok: false, output: `${command} could not be started: ${result.error.message}` };
  }
  return { ok: result.status === 0, output: `${result.stdout ?? ''}${result.stderr ?? ''}` };
}

/** Copy the SquashFS image out of an AppImage without buffering ~160 MB. */
async function extractFilesystemImage(appImagePath: string, imagePath: string): Promise<void> {
  const handle = await open(appImagePath, 'r');
  let offset: number;
  try {
    const header = Buffer.alloc(64);
    await handle.read(header, 0, header.length, 0);
    offset = appImageFilesystemOffset(header);
    const magic = Buffer.alloc(4);
    await handle.read(magic, 0, magic.length, offset);
    if (!isSquashfsSuperblock(magic)) {
      fail(
        `${path.basename(appImagePath)}: no SquashFS superblock at byte ${offset}; ` +
          'the AppImage runtime layout is unrecognized.',
      );
    }
  } finally {
    await handle.close();
  }
  await pipeline(createReadStream(appImagePath, { start: offset }), createWriteStream(imagePath));
}

/**
 * Read the desktop entries an AppImage would install. `unsquashfs` is the
 * reference tool and what Linux CI uses; 7-Zip also reads SquashFS and is what
 * macOS hosts usually have. Neither being present is a failure, not a skip.
 */
async function readAppImageEntries(
  appImagePath: string,
  workDir: string,
): Promise<readonly DesktopEntry[]> {
  const imagePath = path.join(workDir, 'filesystem.squashfs');
  const outputDir = path.join(workDir, 'extracted');
  await extractFilesystemImage(appImagePath, imagePath);

  const attempts: CommandResult[] = [];
  const unsquashfs = run('unsquashfs', ['-n', '-f', '-d', outputDir, imagePath, '*.desktop']);
  attempts.push(unsquashfs);
  if (!unsquashfs.ok) {
    let extracted: CommandResult | null = null;
    for (const sevenZip of ['7z', '7zz', '7za']) {
      const result = run(sevenZip, ['e', '-y', `-o${outputDir}`, imagePath, '*.desktop']);
      attempts.push(result);
      if (result.ok) {
        extracted = result;
        break;
      }
    }
    if (extracted === null) {
      fail(
        `Cannot read desktop entries from ${path.basename(appImagePath)}. ` +
          'Install squashfs-tools (unsquashfs) or 7-Zip.\n' +
          attempts.map((attempt) => `  ${attempt.output.trim()}`).join('\n'),
      );
    }
  }

  return readDesktopEntriesUnder(outputDir, path.basename(appImagePath));
}

/**
 * Read the desktop entries a Debian package installs. `.deb` is a plain `ar`
 * archive, parsed here directly because GNU and BSD `ar` disagree about member
 * naming; only the compressed data tarball needs an external tool.
 */
async function readDebEntries(debPath: string, workDir: string): Promise<readonly DesktopEntry[]> {
  const archive = await readFile(debPath);
  const member = parseArMembers(archive).find((candidate) => candidate.name.startsWith('data.tar'));
  if (member === undefined) {
    fail(`${path.basename(debPath)} has no data.tar member, so it is not a Debian package.`);
  }

  const dataPath = path.join(workDir, member.name);
  await writeFile(dataPath, archive.subarray(member.offset, member.offset + member.size));
  const outputDir = path.join(workDir, 'extracted');
  await mkdir(outputDir, { recursive: true });

  const extracted = run('tar', ['-xf', dataPath, '-C', outputDir]);
  if (!extracted.ok) {
    fail(`Cannot extract ${path.basename(debPath)}:\n  ${extracted.output.trim()}`);
  }

  return readDesktopEntriesUnder(outputDir, path.basename(debPath));
}

async function readDesktopEntriesUnder(
  directory: string,
  artifactName: string,
): Promise<readonly DesktopEntry[]> {
  const entries: DesktopEntry[] = [];
  const pending: string[] = [directory];

  while (pending.length > 0) {
    const current = pending.pop();
    if (current === undefined) break;
    let contents;
    try {
      contents = await readdir(current, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const item of contents) {
      const itemPath = path.join(current, item.name);
      if (item.isDirectory()) {
        pending.push(itemPath);
        continue;
      }
      if (!item.name.endsWith('.desktop')) continue;
      entries.push({
        source: `${artifactName}:${path.relative(directory, itemPath)}`,
        text: await readFile(itemPath, 'utf8'),
      });
    }
  }
  return entries;
}

async function main(): Promise<void> {
  const artifactsDir = path.resolve(process.argv[2] ?? defaultArtifactsDir);
  let artifactNames: readonly string[];
  try {
    artifactNames = await readdir(artifactsDir);
  } catch {
    fail(
      `No packaged Linux artifacts directory at ${artifactsDir}. ` +
        'Run "npm run dist:linux -w docblocks-desktop" first.',
    );
  }

  // `filter` already returns a fresh array, so sorting it in place is safe.
  const appImages = artifactNames.filter((name) => name.endsWith('.AppImage')).sort();
  const debs = artifactNames.filter((name) => name.endsWith('.deb')).sort();
  if (appImages.length === 0 && debs.length === 0) {
    fail(`No AppImage or .deb artifacts were found in ${artifactsDir}.`);
  }

  const workRoot = await mkdtemp(path.join(os.tmpdir(), 'docblocks-linux-launchers-'));
  const entries: DesktopEntry[] = [];
  try {
    for (const [kind, names, read] of [
      ['appimage', appImages, readAppImageEntries],
      ['deb', debs, readDebEntries],
    ] as const) {
      for (const name of names) {
        const workDir = path.join(workRoot, `${kind}-${name}`);
        await mkdir(workDir, { recursive: true });
        entries.push(...(await read(path.join(artifactsDir, name), workDir)));
      }
    }
  } finally {
    await rm(workRoot, { recursive: true, force: true });
  }

  const violations = launcherViolations(entries);
  if (violations.length > 0) {
    process.stderr.write('Packaged Linux launcher policy failed:\n');
    for (const violation of violations) {
      process.stderr.write(`  ${violation.source}: ${violation.detail}\n`);
    }
    process.exit(1);
  }

  for (const entry of entries) {
    process.stdout.write(`  ${entry.source}: Chromium sandbox preserved\n`);
  }
  process.stdout.write(
    `Linux launchers: ${entries.length} desktop ${entries.length === 1 ? 'entry' : 'entries'} ` +
      `across ${appImages.length} AppImage(s) and ${debs.length} .deb(s) keep the Chromium sandbox\n`,
  );
}

await main();
