import { existsSync, statSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface RootPackage {
  readonly scripts?: Readonly<Record<string, string>>;
}

interface WorkspacePackage {
  readonly name?: string;
}

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const agentsPath = path.join(repoRoot, 'AGENTS.md');
const skillsRoot = path.join(repoRoot, '.agents', 'skills');
const beginMarker = '<!-- BEGIN GENERATED: assurance -->';
const endMarker = '<!-- END GENERATED: assurance -->';

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await readFile(file, 'utf8')) as T;
}

async function trackedSkills(): Promise<readonly string[]> {
  const entries = await readdir(skillsRoot, { withFileTypes: true });
  const names = entries
    .filter(
      (entry) => entry.isDirectory() && existsSync(path.join(skillsRoot, entry.name, 'SKILL.md')),
    )
    .map((entry) => entry.name)
    .sort();
  for (const name of names) {
    const source = await readFile(path.join(skillsRoot, name, 'SKILL.md'), 'utf8');
    if (!new RegExp(`^name:\\s*${name}\\s*$`, 'm').test(source)) {
      throw new Error(`.agents/skills/${name}/SKILL.md does not declare name: ${name}`);
    }
  }
  return names;
}

function generatedBlock(skills: readonly string[]): string {
  const skillLines = skills.map(
    (name) => `- \`/${name}\` — source: \`.agents/skills/${name}/SKILL.md\``,
  );
  return [
    beginMarker,
    '',
    '## Assurance and agent skills',
    '',
    '_This section is generated by `npm run generate:agent-guidance`; run `npm run check:agent-guidance` to verify it (not part of `npm run all`)._',
    '',
    '- Canonical local and CI gate: use a Node version satisfying `package.json#engines`, then run `npm run all`; success includes every repository unit/integration test and all locally runnable E2E suites on the current OS.',
    '- Packed public-package consumer check: `npm run check:packages`.',
    '- Assurance-contract freshness check: `npm run check:assurance`.',
    '- Third-party distribution notice drift check: `npm run check:notices`; regenerate after a dependency or bundle change with `npm run generate:notices`.',
    '- All E2E suites together: `npm run test:e2e:all`.',
    '- Individual site E2E: `npm run test:e2e`, `npm run test:e2e:browsers`, and `npm run test:e2e:offline`.',
    '- Individual desktop source E2E: `npm run test:e2e:desktop`.',
    '- Individual desktop packaged-artifact smoke: `npm run test:e2e:desktop:packaged`.',
    '- Individual VS Code Web E2E: `npm run test:e2e:vscode`.',
    '- Individual VS Code desktop extension-host E2E: `npm run test:e2e:vscode:desktop`.',
    '',
    'Tracked repository skills:',
    '',
    ...skillLines,
    '',
    '`reports/` is gitignored; audit output stays local unless the team explicitly promotes it.',
    '',
    endMarker,
  ].join('\n');
}

function replaceGeneratedBlock(source: string, replacement: string): string {
  const start = source.indexOf(beginMarker);
  const end = source.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error('AGENTS.md is missing the generated assurance markers');
  }
  return `${source.slice(0, start)}${replacement}${source.slice(end + endMarker.length)}`;
}

async function guideSources(
  agents: string,
  skills: readonly string[],
): Promise<readonly [string, string][]> {
  const sources: [string, string][] = [['AGENTS.md', agents]];
  for (const skill of skills) {
    const relative = `.agents/skills/${skill}/SKILL.md`;
    sources.push([relative, await readFile(path.join(repoRoot, relative), 'utf8')]);
  }
  return sources;
}

function assertNoStaleTokens(sources: readonly [string, string][]): void {
  const forbidden = ['..\\qualla', '../qualla', '.Codex/skills', 'markdownEditorProvider'];
  for (const [name, source] of sources) {
    for (const token of forbidden) {
      if (source.includes(token)) throw new Error(`${name} still references obsolete ${token}`);
    }
    if (/\b\d+\s+(?:passing|pending|failing|tests?)\b/i.test(source)) {
      throw new Error(`${name} encodes a test count; report counts from the current run instead`);
    }
  }
}

function assertDocumentedScripts(
  sources: readonly [string, string][],
  scripts: Readonly<Record<string, string>>,
): void {
  const pattern = /npm run ([a-zA-Z0-9:_-]+)/g;
  for (const [name, source] of sources) {
    for (const match of source.matchAll(pattern)) {
      if (!(match[1] in scripts)) {
        throw new Error(`${name} references missing root script: npm run ${match[1]}`);
      }
    }
  }
}

function assertReferencedFiles(sources: readonly [string, string][]): void {
  const pattern = /packages\/[A-Za-z0-9._/-]+\.(?:tsx|ts|json|css|md|yaml|yml)/g;
  for (const [name, source] of sources) {
    for (const match of source.matchAll(pattern)) {
      const candidate = match[0];
      if (!existsSync(path.join(repoRoot, candidate))) {
        throw new Error(`${name} references missing file: ${candidate}`);
      }
    }
  }
}

/**
 * Directory references rot the same way file references do, and only the file
 * form was checked -- which is how the guidance came to point at
 * `packages/react/src/fonts/` for years, a directory that has never existed.
 *
 * A trailing slash is what marks a directory reference; without it there is no
 * way to tell `packages/react/src` from an extension-less prose fragment.
 */
function assertReferencedDirectories(sources: readonly [string, string][]): void {
  const pattern = /packages\/[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._-]+)*\//g;
  for (const [name, source] of sources) {
    for (const match of source.matchAll(pattern)) {
      const candidate = match[0].replace(/\/$/, '');
      // Skip glob-ish or placeholder segments; they are patterns, not paths.
      if (/[*?<>]/.test(candidate)) continue;
      const resolved = path.join(repoRoot, candidate);
      if (!existsSync(resolved)) {
        throw new Error(`${name} references missing directory: ${candidate}/`);
      }
      if (!statSync(resolved).isDirectory()) {
        throw new Error(`${name} references ${candidate}/ as a directory, but it is a file`);
      }
    }
  }
}

async function assertWorkspaceTable(agents: string): Promise<void> {
  const packageDirectories = (
    await readdir(path.join(repoRoot, 'packages'), { withFileTypes: true })
  )
    .filter(
      (entry) =>
        entry.isDirectory() &&
        existsSync(path.join(repoRoot, 'packages', entry.name, 'package.json')),
    )
    .map((entry) => entry.name)
    .sort();
  for (const directory of packageDirectories) {
    const manifest = await readJson<WorkspacePackage>(
      path.join(repoRoot, 'packages', directory, 'package.json'),
    );
    if (!manifest.name) throw new Error(`packages/${directory}/package.json has no package name`);
    const rowPrefix = `| \`packages/${directory}\``;
    if (!agents.includes(rowPrefix) || !agents.includes(`\`${manifest.name}\``)) {
      throw new Error(
        `AGENTS.md package table is stale for packages/${directory} (${manifest.name})`,
      );
    }
  }
}

async function main(): Promise<void> {
  const rootPackage = await readJson<RootPackage>(path.join(repoRoot, 'package.json'));
  const scripts = rootPackage.scripts ?? {};
  const skills = await trackedSkills();
  const expectedBlock = generatedBlock(skills);
  const currentAgents = await readFile(agentsPath, 'utf8');
  const expectedAgents = replaceGeneratedBlock(currentAgents, expectedBlock);

  if (process.argv.includes('--write')) {
    await writeFile(agentsPath, expectedAgents);
    process.stdout.write('Updated generated assurance guidance in AGENTS.md.\n');
    return;
  }
  if (currentAgents !== expectedAgents) {
    throw new Error(
      'AGENTS.md generated assurance guidance is stale; run npm run generate:agent-guidance',
    );
  }

  const sources = await guideSources(currentAgents, skills);
  assertNoStaleTokens(sources);
  assertDocumentedScripts(sources, scripts);
  assertReferencedFiles(sources);
  assertReferencedDirectories(sources);
  await assertWorkspaceTable(currentAgents);
  process.stdout.write(
    `Agent guidance is fresh for ${skills.length} tracked skills and all workspaces.\n`,
  );
}

try {
  await main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}
