/**
 * Derive the VS Code webview's theme fonts from the site's.
 *
 * Squisq ships no `@font-face` rules: every stack in `AVAILABLE_FONT_STACKS`
 * that names a `googleFontFamily` expects the host page to supply the faces. The
 * site and the desktop renderer both carry the full set; the webview's copy was
 * hand-filtered to the Write-canvas schemes and silently lost eight families
 * that Squisq document themes still select, so those documents rendered in a
 * fallback face in VS Code alone.
 *
 * Generating the file removes the drift rather than fixing one instance of it.
 * `npm run check:site-fonts` is the gate that proves the result.
 *
 *   npm run generate:webview-fonts
 *   npm run generate:webview-fonts -- --check   # fail instead of writing
 *
 * The webview loads faces through Vite, so the url()s are rewritten relative to
 * the stylesheet and the files are copied next to it. The site keeps absolute
 * `/fonts/...` urls because it serves them from its public root.
 */

import { copyFile, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AVAILABLE_FONT_STACKS } from '@bendyline/squisq';
import { requiredFamilies } from './font-parity-policy.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const siteFontsCss = path.join(repoRoot, 'packages/site/public/fonts/fonts.css');
const siteFontsDir = path.join(repoRoot, 'packages/site/public/fonts');
const webviewFontsCss = path.join(repoRoot, 'packages/vscode/webview/src/fonts.css');
const webviewFontsDir = path.join(repoRoot, 'packages/vscode/webview/src/fonts');

/**
 * Families the webview needs beyond Squisq's registry.
 *
 * The Write-canvas font schemes in `packages/react/src/preferences/write-canvas.ts`
 * are a DocBlocks concept, so they are not in Squisq's stack list. Neither is
 * the fixed UI face, which gives the shell chrome a deterministic alternative to
 * `system-ui` — see the block that declares it in the site's fonts.css.
 */
const ADDITIONAL_FAMILIES = ['Hanken Grotesk', 'DocBlocks Fixed UI'] as const;

const HEADER = `/* Self-hosted theme fonts for the DocBlocks VS Code webview (Latin + Latin
 * Extended).
 *
 * GENERATED by scripts/generate-webview-fonts.ts from
 * packages/site/public/fonts/fonts.css — do not edit by hand. Run
 * \`npm run generate:webview-fonts\` after changing the site's fonts.
 *
 * Every Squisq font stack that names a googleFontFamily is included: Squisq
 * ships no @font-face rules, so a family missing here renders in a fallback
 * face on this surface alone. url()s are relative so Vite bundles the files
 * into dist/webview, where they load under the webview CSP. */
`;

function fontFaceBlocks(css: string): readonly string[] {
  return [...css.matchAll(/@font-face\s*\{[^}]*\}/gu)].map((match) => match[0]);
}

function blockFamily(block: string): string | null {
  const declaration = /font-family\s*:\s*([^;]+)/u.exec(block);
  if (!declaration) return null;
  return declaration[1]!.trim().replace(/^['"]|['"]$/gu, '');
}

function referencedFiles(block: string): readonly string[] {
  return [...block.matchAll(/url\(['"]?\/fonts\/([^'")]+\.woff2)['"]?\)/gu)].map(
    (match) => match[1]!,
  );
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const wanted = new Set([...requiredFamilies(AVAILABLE_FONT_STACKS), ...ADDITIONAL_FAMILIES]);

  const siteCss = await readFile(siteFontsCss, 'utf8');
  const blocks = fontFaceBlocks(siteCss).filter((block) => {
    const family = blockFamily(block);
    return family !== null && wanted.has(family);
  });

  const coveredFamilies = new Set(
    blocks.map((block) => blockFamily(block)).filter((family): family is string => family !== null),
  );
  const uncovered = [...wanted].filter((family) => !coveredFamilies.has(family));
  if (uncovered.length > 0) {
    throw new Error(
      `The site stylesheet declares no faces for: ${uncovered.join(', ')}. ` +
        'Add them to packages/site/public/fonts/fonts.css first.',
    );
  }

  const css = `${HEADER}\n${blocks
    .map((block) => block.replace(/url\(['"]?\/fonts\//gu, "url('./fonts/"))
    .join('\n\n')}\n`;
  const files = [...new Set(blocks.flatMap((block) => referencedFiles(block)))].sort();

  if (checkOnly) {
    const current = await readFile(webviewFontsCss, 'utf8').catch(() => '');
    const present = new Set(
      (await readdir(webviewFontsDir).catch(() => [])).filter((file) => file.endsWith('.woff2')),
    );
    const stale = current !== css || files.some((file) => !present.has(file));
    if (stale) {
      throw new Error(
        'packages/vscode/webview/src/fonts.css is stale. Run `npm run generate:webview-fonts`.',
      );
    }
    process.stdout.write(`VS Code webview fonts are current (${files.length} files).\n`);
    return;
  }

  await writeFile(webviewFontsCss, css);
  await mkdir(webviewFontsDir, { recursive: true });

  // Remove faces the site no longer supplies before copying, so a renamed file
  // cannot linger and be served alongside its replacement.
  const keep = new Set(files);
  for (const existing of await readdir(webviewFontsDir).catch(() => [])) {
    if (existing.endsWith('.woff2') && !keep.has(existing)) {
      await rm(path.join(webviewFontsDir, existing));
    }
  }
  for (const file of files) {
    await copyFile(path.join(siteFontsDir, file), path.join(webviewFontsDir, file));
  }

  process.stdout.write(
    `VS Code webview fonts: ${coveredFamilies.size} families, ${files.length} files.\n`,
  );
}

await main();
