/** The starter document created for an empty DocBlocks workspace. */
export const WELCOME_DOCUMENT_PATH = '/aboutDocBlocks.md';

/**
 * Keep annotations attached to headings: each heading becomes a deliberate
 * presentation block while the Markdown remains readable as ordinary prose.
 */
export const WELCOME_DOCUMENT_CONTENT = [
  '---',
  'squisq-theme: warm-earth',
  'squisq-cover-slide: false',
  '---',
  '',
  '# DocBlocks: one Markdown file, many finished forms {[title subtitle="Local-first writing for pages, documents, slideshows, and video"]}',
  '',
  'Write in plain Markdown. Shape it visually. Keep it portable.',
  '',
  '## A document editor that never asks you to stop owning the document {[factCard]}',
  '',
  'DocBlocks pairs a friendly visual writing surface with the durable source format you already know. There is no account to create, no proprietary document to rescue later, and no requirement to send your work to a hosted editor.',
  '',
  '## One source, four ways to publish {[diagram]}',
  '',
  '```diagram',
  '+------------+',
  '|  Markdown  |',
  '+-----+------+',
  '      |',
  '  +---+------+------------+-----------+',
  '  |          |            |           |',
  '  v          v            v           v',
  '+-------+ +---------+ +------------+ +-------+',
  '| Pages | |Documents| | Slideshows | | Video |',
  '+-------+ +---------+ +------------+ +-------+',
  '```',
  '',
  '## Write visually, then look under the hood whenever you like {[content]}',
  '',
  'Use the rich editor for headings, lists, tables, links, images, media, and everyday formatting. Switch to raw Markdown for exact control. Add themes, transform styles, and squiggly-square section annotations when a passage deserves its own visual treatment. The readable `.md` source stays at the center of the workflow.',
  '',
  '## Preview the finished idea before you export it {[list]}',
  '',
  '- **Document** — Read the work as a polished, continuous document.',
  '- **Page** — See how it behaves as a web page.',
  '- **Slideshow** — Step through headings as designed presentation blocks.',
  '- **Video** — Rehearse timing, motion, narration, and media in a player-ready view.',
  '',
  '## Local or installed: choose the workspace that fits {[twoColumn header="Work where your files make sense" left="Web|Browser-local workspaces or folders you explicitly grant" right="Desktop|Real folders, native menus, file opening, and updates"]}',
  '',
  '## In the project or in the pipeline {[twoColumn header="The same Markdown keeps moving" left="VS Code|Rich editing beside tabs, source control, and the project tree" right="CLI + MCP|Build, serve, convert, render, inspect, validate, and automate"]}',
  '',
  '## The quiet conveniences are there, too {[list]}',
  '',
  '- **Workspaces and file navigation** keep related documents organized without hiding their source.',
  '- **Automatic saving** protects the active revision while still surfacing conflicts or save errors.',
  '- **Optional version history** keeps plain sibling revisions when you want a trail of changes.',
  '- **Copy-by-link sharing** creates a bounded Markdown copy that can open directly in a chosen Play view.',
  '- **Offline-ready, local-first storage** keeps browser work on this device and native work inside folders you choose.',
  '',
  '## Export without rebuilding the document {[list]}',
  '',
  '- Create **Word documents and PDFs** for review, printing, and fixed-layout sharing.',
  '- Create **PowerPoint decks** from the same annotated sections you preview as a slideshow.',
  '- Publish **HTML pages, packaged HTML, and EPUB e-books**.',
  '- Keep portable **Markdown or DBK bundles** with their media assets.',
  '- Use the linked CLI registry for **spreadsheets, MP4 video, animated GIF, batch conversion, and more**.',
  '',
  '## Local-first is concrete, not decorative {[quote]}',
  '',
  '> Your browser workspace stays on this device. Native folders are opened only when you choose them. Your Markdown remains useful in DocBlocks, Git, a terminal, another editor, or an AI-assisted workflow.',
  '',
  '## Agents get document tools, not a blank check {[factCard]}',
  '',
  'The local MCP server converts plain text or Markdown directly and can optionally inspect, preview, or compare documents. Results remain temporary session artifacts until they are deliberately saved, and filesystem access begins with explicit roots rather than assumed authority.',
  '',
  '## Start with three small moves {[list]}',
  '',
  '1. Create a document with **New file** in the file pane.',
  '2. Write visually or in Markdown source; switch views whenever it helps.',
  '3. Open **Play** or **Export** when the idea is ready to become something else.',
  '',
  '## Explore DocBlocks {[list]}',
  '',
  '- [Desktop app](https://docblocks.com/desktop/) — macOS, Windows, and Linux.',
  '- [VS Code extension](https://docblocks.com/vscode/) — rich Markdown editing inside a workspace.',
  '- [CLI and MCP server](https://docblocks.com/cli/) — conversion, rendering, and agent workflows.',
  '- [Supported formats](https://docblocks.com/formats/) — current import and export directions.',
  '- [Documentation](https://docblocks.com/docs/) — guides for using and extending DocBlocks.',
].join('\n');
